<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'console.command.debug_autowiring' shared service.

require_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
require_once $this->targetDirs[3].'/vendor/symfony/dependency-injection/ContainerAwareInterface.php';
require_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Command/ContainerAwareCommand.php';
require_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Command/ContainerDebugCommand.php';
require_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Command/DebugAutowiringCommand.php';

$this->services['console.command.debug_autowiring'] = $instance = new \Symfony\Bundle\FrameworkBundle\Command\DebugAutowiringCommand();

$instance->setName('debug:autowiring');

return $instance;
