<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'cache.system' shared service.

require_once $this->targetDirs[3].'/vendor/psr/cache/src/CacheItemPoolInterface.php';
require_once $this->targetDirs[3].'/vendor/symfony/cache/Adapter/AdapterInterface.php';
require_once $this->targetDirs[3].'/vendor/psr/log/Psr/Log/LoggerAwareInterface.php';
require_once $this->targetDirs[3].'/vendor/symfony/cache/ResettableInterface.php';
require_once $this->targetDirs[3].'/vendor/psr/log/Psr/Log/LoggerAwareTrait.php';
require_once $this->targetDirs[3].'/vendor/symfony/cache/Traits/AbstractTrait.php';
require_once $this->targetDirs[3].'/vendor/symfony/cache/Adapter/AbstractAdapter.php';

return $this->services['cache.system'] = \Symfony\Component\Cache\Adapter\AbstractAdapter::createSystemCache('yoie219eZH', 0, '-3xwIss93NsLm78FBgVkuF', ($this->targetDirs[0].'/pools'), ${($_ = isset($this->services['logger']) ? $this->services['logger'] : $this->services['logger'] = new \Symfony\Component\HttpKernel\Log\Logger()) && false ?: '_'});
