<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (!class_exists(\ContainerVmzkxwl\srcDevDebugProjectContainer::class, false)) {
    require __DIR__.'/ContainerVmzkxwl/srcDevDebugProjectContainer.php';
}

if (!class_exists(srcDevDebugProjectContainer::class, false)) {
    class_alias(\ContainerVmzkxwl\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerVmzkxwl\srcDevDebugProjectContainer();
